/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Diego Luján García (https://sketchfab.com/diegoluga)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/ab11ebff89224f03bd75efede1164cf6
title: Male Full Body Ecorche
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/scene.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.mesh_0.geometry} material={materials.defaultMat_12} />
        <mesh geometry={nodes.mesh_1.geometry} material={materials.defaultMat_11} />
        <mesh geometry={nodes.mesh_2.geometry} material={materials.defaultMat_10} />
        <mesh geometry={nodes.mesh_3.geometry} material={materials.defaultMat_9} />
        <mesh geometry={nodes.mesh_4.geometry} material={materials.material_1} />
        <mesh geometry={nodes.mesh_5.geometry} material={materials.defaultMat_8} />
        <mesh geometry={nodes.mesh_6.geometry} material={materials.defaultMat_7} />
        <mesh geometry={nodes.mesh_7.geometry} material={materials.defaultMat_6} />
        <mesh geometry={nodes.mesh_8.geometry} material={materials.defaultMat_5} />
        <mesh geometry={nodes.mesh_9.geometry} material={materials.defaultMat_4} />
        <mesh geometry={nodes.mesh_10.geometry} material={materials.defaultMat_3} />
        <mesh geometry={nodes.mesh_11.geometry} material={materials.defaultMat_2} />
        <mesh geometry={nodes.mesh_12.geometry} material={materials.defaultMat_1} />
        <mesh geometry={nodes.mesh_13.geometry} material={materials.material_0} />
        <mesh geometry={nodes.mesh_14.geometry} material={materials.defaultMat_0} />
        <mesh geometry={nodes.mesh_15.geometry} material={materials.defaultMat} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.glb')
